### ISSUE TITLE
not work at all

### ISSUE THREAD

**Issue by GVALFER** [metcoder95/fastify-ip#44]
**Describe the bug**
This simple plugin does not work at all

```
import fastifyIp from "fastify-ip";
app.register(fastifyIp);

app.get("/ip", async (req, reply) => {
  return { ip: req.ip };
});

console log print
{"ip":""}

```

Any suggestion?

**Comment by metcoder95** [comment]
Can you provide an 
[Minimum Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example)?

A quick guess its that the `ip` of your request might not be populated from the request itself, not from within the plugin.
