### ISSUE TITLE
FST_ERR_DEC_ALREADY_PRESENT error when set `trustProxy` to true

### ISSUE THREAD

**Issue by Dafyh** [metcoder95/fastify-ip#50]
**Describe the bug**
If the `trustProxy` option is set to true, the following error occurs: `FST_ERR_DEC_ALREADY_PRESENT`.

**To Reproduce**
```js
'use strict'
const tap = require('tap')
const fastify = require('fastify')
const plugin = require('../')

tap.test('Plugin#Decoration', scope => {
  scope.test('Throw a FST_ERR_DEC_ALREADY_PRESENT error', async t => {
    await fastify({ trustProxy: true }).register(plugin).ready()
  })
})
```

**Expected behavior**
Should not return any errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/3f630251-a409-4262-b6a2-aafedbca6141)

**Comment by metcoder95** [comment]
Thanks for the report!

We can provide two properties at the same time, if the `request.ip` has been already set, we can just skip it.

The second one can always be set, something like `realIp` or `inferredIp` (or similar).

Would you like to submit a PR?

**Comment by Dafyh** [comment]
Yes, I can do a PR.

However, we could redefine the getter `ip` in the hook `preHandler` instead of adding a property in the case where trustProxy is `true` (ip, ips, hostname and protocol are present) ?

**Comment by Dafyh** [comment]
For example :
```js
const isTrustProxyOn = [
  'ip',
  'ips',
  'hostname',
  'protocol'
].every((key) => instance.hasRequestDecorator(key))

if (isTrustProxyOn) {
  async function redefineIpDecorator (request) {
    Object.defineProperty(request, 'ip', {
      get () {
        return ipDecorator.getter.apply(request)
      }
    })
  }

  instance.addHook('preHandler', redefineIpDecorator)
} else {
  instance.decorateRequest('ip', ipDecorator)
}
```
Where `ipDecorator` is the object with the getter.

**Comment by metcoder95** [comment]
sgtm. i’d just recommend to not re define the property but rather just assign it.

let’s also document this in the documentation

**Comment by Dafyh** [comment]
Unfortunately, I can't assign a value as the setter is not implemented (TypeError). We could also propose a PR on fastify, but the simplest solution would be to redefine the property into `fastify-ip` 😊.

I will do a PR in any cases.

[see](https://github.com/fastify/fastify/blob/9a1be751bac5e02a92e7ec070912489f4f962c4f/lib/request.js#L106)

**Comment by metcoder95** [comment]
ah good callout, then that's fine 👍

**Comment by fraxken** [comment]
Thanks for the fast answer and the release ❤️ 🚀
